"""ZzCode memory helpers."""

from .context import (
    MemoryContext,
    build_memory_context,
    format_auto_memory_index,
    format_compact_summary,
    format_current_session_memory,
    format_instruction_memories,
    format_session_notes,
)
from .auto import (
    AUTO_MEMORY_TYPES,
    DEFAULT_AUTO_MEMORY_INDEX,
    DEFAULT_AUTO_MEMORY_MAX_CHARS,
    AutoMemoryHeader,
    ensure_auto_memory,
    format_auto_memory_manifest,
    get_auto_memory_dir,
    get_auto_memory_index_path,
    read_auto_memory_file,
    read_auto_memory_index,
    scan_auto_memory_files,
)
from .instruction import InstructionMemoryFile, get_instruction_memory_files
from .loader import LoadedInstructionMemory, load_instruction_memories
from .session import (
    DEFAULT_COMPACT_CHAR_THRESHOLD,
    DEFAULT_COMPACT_KEEP_ITEMS,
    DEFAULT_COMPACT_SUMMARY_LIMIT,
    DEFAULT_SESSION_HISTORY_LIMIT,
    SessionCompactResult,
    ShortTermSessionMemory,
)
from .session_scope import (
    DEFAULT_SESSION_MEMORY_MAX_CHARS,
    DEFAULT_SESSION_MEMORY_TEMPLATE,
    SESSION_MEMORY_MAX_SECTION_TOKENS,
    SESSION_MEMORY_MAX_TOTAL_TOKENS,
    SessionMemoryTruncateResult,
    SessionScope,
    TranscriptRecorder,
    analyze_session_memory_sections,
    build_session_memory_size_reminders,
    create_session_scope,
    ensure_session_scope,
    get_session_dir,
    get_sessions_dir,
    is_session_memory_empty,
    read_current_session_memory,
    truncate_session_memory_for_compact,
)
from .session_notes import (
    DEFAULT_SESSION_NOTES_MAX_CHARS,
    DEFAULT_SESSION_NOTES_TEMPLATE,
    ensure_session_notes_file,
    get_session_notes_path,
    read_session_notes,
)

__all__ = [
    "DEFAULT_COMPACT_CHAR_THRESHOLD",
    "DEFAULT_COMPACT_KEEP_ITEMS",
    "DEFAULT_COMPACT_SUMMARY_LIMIT",
    "DEFAULT_AUTO_MEMORY_INDEX",
    "DEFAULT_AUTO_MEMORY_MAX_CHARS",
    "DEFAULT_SESSION_HISTORY_LIMIT",
    "DEFAULT_SESSION_MEMORY_MAX_CHARS",
    "DEFAULT_SESSION_MEMORY_TEMPLATE",
    "SESSION_MEMORY_MAX_SECTION_TOKENS",
    "SESSION_MEMORY_MAX_TOTAL_TOKENS",
    "DEFAULT_SESSION_NOTES_MAX_CHARS",
    "DEFAULT_SESSION_NOTES_TEMPLATE",
    "AUTO_MEMORY_TYPES",
    "AutoMemoryHeader",
    "InstructionMemoryFile",
    "LoadedInstructionMemory",
    "MemoryContext",
    "SessionCompactResult",
    "SessionMemoryTruncateResult",
    "SessionScope",
    "ShortTermSessionMemory",
    "TranscriptRecorder",
    "analyze_session_memory_sections",
    "build_memory_context",
    "build_session_memory_size_reminders",
    "create_session_scope",
    "ensure_auto_memory",
    "ensure_session_scope",
    "ensure_session_notes_file",
    "format_auto_memory_manifest",
    "format_auto_memory_index",
    "format_compact_summary",
    "format_current_session_memory",
    "format_instruction_memories",
    "format_session_notes",
    "get_auto_memory_dir",
    "get_auto_memory_index_path",
    "get_instruction_memory_files",
    "get_session_notes_path",
    "get_session_dir",
    "get_sessions_dir",
    "is_session_memory_empty",
    "load_instruction_memories",
    "read_auto_memory_file",
    "read_auto_memory_index",
    "scan_auto_memory_files",
    "read_session_notes",
    "read_current_session_memory",
    "truncate_session_memory_for_compact",
]
